	
JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
	Chapter1_Array_String.java\
	Main.java 

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class